### ISSUE TITLE
모델별 아이콘 결정

### ISSUE THREAD

**Issue by rest515** [parti-coop/Deprecated-catan-web#5]
폰트어썸에서 카누, 논의, 의견, 제안의 아이콘을 결정하고 사이트에 적용합니다.

**Comment by rest515** [comment]
http://fontawesome.io/ 폰트어썸 사이트입니다.

**Comment by berry502** [comment]
고객센터 <i class="fa fa-envelope-o"></i> <i class="fa fa-envelope"></i>

**Comment by berry502** [comment]
승선요청하기 http://fontawesome.io/icon/user-plus/

**Comment by berry502** [comment]
http://canoe.parti.xyz/canoeing-the-canoe 카누 상세페이지의 [논의 시작하기] 버튼 http://fontawesome.io/icon/flag-o/

**Comment by berry502** [comment]
best에는 하트는 빼고 트로피 아이콘만 있었으면 합니다.

**Comment by berry502** [comment]
best / worst 는 찬성, 반대 아이콘과 같은 하트와 금지 라벨만 남겼으면 합니다. (세우거나 엎은 트로피가 훨 귀엽긴한데ㅜㅜ) 의견 한번 들어보고 싶네요

**Comment by dalikim** [comment]
네 좋습니다
